### ISSUE TITLE
demo link is showing blank

### ISSUE THREAD

**Issue by arunpratap26** [conficient/BlazorDynamicList#3] opened 2019-06-14 07:24 UTC
demo is hosted at https://blazordynamiclist.azurewebsites.net  is not working

![Untitled](https://user-images.githubusercontent.com/47097845/59490900-6e214b80-8ea3-11e9-96f0-62a973e1d5ba.png)

**Comment by conficient** [comment] 2019-06-14 09:05
Thanks for the warning, I was aware - it seems preview 6 has issues when publishing Blazor apps - see https://github.com/aspnet/AspNetCore/issues/10878 - I've intentionally left it broken until this is fixed

**Comment by arunpratap26** [comment] 2019-06-14 11:12
thank you should I close this issue or you will?

**Comment by conficient** [comment] 2019-06-14 14:28
I'll close it when MS fixes the cause and the site is working again, thx

**Comment by conficient** [comment] 2019-07-12 09:20
Found a fix for this issue and demo site is now working again

**Closed as completed by conficient** 2019-07-12 09:20 UTC
